set (PACKAGE_VERSION "1.6.2")

if ("${PACKAGE_FIND_VERSION_MAJOR}" EQUAL 1 AND "${PACKAGE_FIND_VERSION_MINOR}" EQUAL 6 AND "${PACKAGE_FIND_VERSION_PATCH}" EQUAL 2 )
	set(PACKAGE_VERSION_COMPATIBLE true)
	set(PACKAGE_VERSION_EXACT true)
endif ()


